$mainMod = SUPER

# (S) Special throw-away workspace
workspace = special:temp, gapsout:0, border:false, rounding:false
binddp = $mainMod, S, Open a special throw-away workspace, togglespecialworkspace, temp
binddp = $mainMod SHIFT, S, Send window to the special throw-away workspace, movetoworkspace, special:temp

# (W) Browser
binddp = $mainMod, W, Open a private browser workspace, togglespecialworkspace, private
binddp = $mainMod SHIFT, Send window to the private browser workspace, W, movetoworkspace, special:private
gesture = 3, up, special, private
## Private zen instance by default
workspace = special:private, gapsout:0, border:false, rounding:false, on-created-empty:(zen -new-instance -P private --name zen-private --private-window)
windowrule = workspace special:private, match:class (zen-private)
windowrule = no_blur on, match:class (zen-private)

# (N) Notes
binddp = $mainMod, N, Open a notes workspace, togglespecialworkspace, notes
binddp = $mainMod SHIFT, N, Send window to the notes workspace, movetoworkspace, special:notes
## Obsidian by default
workspace = special:notes, gapsout:0, border:false, rounding:false, on-created-empty:uwsm-app -- obsidian
windowrule = workspace special:notes, match:initial_class (obsidian)

# (D) Discord
binddp = $mainMod, D, Open a Discord workspace, togglespecialworkspace, discord
binddp = $mainMod SHIFT, D, Send window to the Discord workspace, movetoworkspace, special:discord
## Equibop by default
workspace = special:discord, gapsout:0, border:false, rounding:false, on-created-empty:equibop
windowrule = workspace special:discord, match:class ^(equibop)$

# (T) Telegram
binddp = $mainMod, T, Open a Telegram workspace, togglespecialworkspace, telegram
binddp = $mainMod SHIFT, T, Send window to the Telegram workspace, movetoworkspace, special:telegram
## Telegram by default
workspace = special:telegram, gapsout:0, border:false, rounding:false, on-created-empty:Telegram
windowrule = workspace special:telegram, match:class (org.telegram.desktop)
