# Hide Bitwarden from screen share
windowrule = no_screen_share on, match:class ^(Bitwarden)$

# Browser popup for auth
windowrule = no_screen_share on, tag +floating-window, match:title ^Extension: \(Bitwarden Password Manager\).*$
