# Browser types
windowrule = tag +chromium-based-browser, class:^((google-)?[cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable|helium)$
windowrule = tag +firefox-based-browser, class:^([fF]irefox|zen|librewolf).*$
windowrule = tag +firefox-based-browser-private, class:^([fF]irefox|zen|librewolf).*-private$

# Only a subtle opacity change, but not for video sites
windowrule = opacity 1 0.97, tag:chromium-based-browser
windowrule = opacity 1 0.97, tag:firefox-based-browser

# Firefox
## Private browser overlay
windowrule = opacity 0.85 override 0.7 override, tag:firefox-based-browser-private

## Extension update popups
windowrule = float, move 0 200, tag:firefox-based-browser, title:^Extension: \(.*\).*$
windowrule = float, noinitialfocus, move 0 200, tag:firefox-based-browser, title:^()$

# Some video sites should never have opacity applied to them
windowrule = opacity 1.0 1.0, title:(.*- YouTube.*)
