# Browser types
windowrule = tag +chromium-based-browser, match:class ^((google-)?[cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable|helium)$
windowrule = tag +firefox-based-browser, match:class ^([fF]irefox|zen|librewolf).*$
windowrule = tag +firefox-based-browser-private, match:class ^([fF]irefox|zen|librewolf).*-private$

# Only a subtle opacity change, but not for video sites
windowrule = opacity 1 0.97, match:tag chromium-based-browser
windowrule = opacity 1 0.97, match:tag firefox-based-browser

# Firefox
## Private browser overlay
windowrule = opacity 0.85 override 0.7 override, match:tag firefox-based-browser-private

## Extension update popups
windowrule = float on, move 0 200, match:tag firefox-based-browser, match:title ^Extension: \(.*\).*$
windowrule = float on, no_initial_focus on, move 0 200, match:tag firefox-based-browser, match:title ^()$

# Some video sites should never have opacity applied to them
windowrule = opacity 1.0 1.0, match:title ^(.*- YouTube.*)$
