# Picture-in-picture overlays
windowrule = tag +pip, match:title ^(Picture.?in.?[Pp]icture)$

windowrule {
    name = PiP
    match:tag = pip

    float = on
    pin = on
    size = 600 338
    keep_aspect_ratio = on
    border_size = 0
    opacity = 1 1
    move = 100%-w-40 4%
}

# mpv overrides
windowrule {
    name = mpv
    match:class = ^(mpv)$
    
    keep_aspect_ratio = on
    opacity = 1 1
}
## Floating mpv
windowrule {
    name = mpv PiP
    match:class = ^(mpv)$
    match:float = on
    
    border_size = 0
}
