windowrule = workspace 3, match:class ^steam_app_.*$

# Float Steam
windowrule = size 460 800, float on, center on, match:class steam, match:title Friends List

windowrule = idle_inhibit fullscreen, match:class steam
