# Floating windows
windowrule = float on, match:tag floating-window
windowrule = center on, match:tag floating-window
windowrule = size 800 600, match:tag floating-window

windowrule = tag +floating-window, match:class (org\.gnome\.NautilusPreviewer)
