# Floating windows
windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 800 600, tag:floating-window

windowrule = tag +floating-window, class:(org\.gnome\.NautilusPreviewer)
