## Use a custom provided theme
include current-theme.conf

# Window
window_padding_width 14
## Don't confirm closing
confirm_os_window_close 0

# Styling
## Tabs are shown as a continuous line with “fancy” separators.
tab_bar_style powerline
### "/"-like separator
tab_powerline_style slanted
